### ISSUE TITLE
Overlap with Github content when scrolling

### ISSUE THREAD

**Issue by AprilNEA** [reorx/github-toc-sidebar#3]
![image](https://github.com/reorx/github-toc-sidebar/assets/37977109/e5d0c32d-83f3-4fc8-8cd4-6f4b1d6b9a10)

There is a chance of overlap with Github content when scrolling.

**Comment by reorx** [comment]
Would be appreciated if you can provide a GitHub link that can reproduce
this problem

Sincerely,
Xiao Meng

**Comment by AprilNEA** [comment]
Sorry to say, but I realized it was my other Chrome Extension [refined-github](https://github.com/refined-github/refined-github) that was conflicting with it.

Uncheck the following options to resolve the conflict:

<img width="606" alt="image" src="https://github.com/reorx/github-toc-sidebar/assets/37977109/4f866ede-0baa-44d2-95b5-499cac950c74">

I can assist in adding that note to the README for this repository if needed.
